### ISSUE TITLE
Ring working only once after adapter installation

### ISSUE THREAD

**Issue by mark77-DE** [schmupu/ioBroker.ring#15] opened 2020-01-02 14:12 UTC
System setup:
iobroker in buanet Docker container
Adapter Version: 1.0.6
npm: 6.13.4
nodejs: 10.18.0

After installation I can ring the doorbell once, after that, no more changes within the states.
Snapshot request is still working and updating pictures.
More information needed?

Reccomondation:
Possibility to auto delete old snapshot files.

Notice:
If users installing ring on buanets Docker image, you also need to install ffmpeg

**Comment by schmupu** [comment] 2020-01-02 15:06
in the moment I will Not fix anything. The API does not work anymore

**Comment by marc2016** [comment] 2020-02-01 21:56
This [issue](https://github.com/dgreif/ring/issues/246) on ring-client-api project helped me.
After I set the cameraDingsPollingSeconds from 1 to 2 in the file ringapiclient.js line 129 and 136, I receive the newDing events again. Maybe you can push this workaround until the problem is analyzed and fixed in ring-client-api project.

**Comment by marc2016** [comment] 2020-02-02 20:22
I have analyzed this issue. The ring-api-client is always initialized when the function ringer() in ring.js is called. This causes multiple instances of the client and somehow the right subscription is not triggered.
I have deleted line 595 in file ring.js and it seems to work.

**Comment by schmupu** [comment] 2020-05-01 07:08
The ring-api-client is only called in function ring() if no ring instance exist. 
The problem shall be fixed now with the new ring-api-client version. 
Please download the now ring adapter from GitHub and check. If it does not work, please reopen the issue

**Closed by schmupu** 2020-05-01 07:08 UTC
